### ISSUE TITLE
세부장소 장소성 추출을 위한 필요 목록

### ISSUE THREAD

**Issue by kj0821** [shinbyh/kaist-placeness-api#1]
세부장소 장소성 추출을 위해서 몇가지 패키지를 사용합니다.

모두 실행하기 위해서는 아래 두 가지 패키지가 필요합니다.
1) python-firebase ($pip install python-firebase)
2) konlpy (http://konlpy-ko.readthedocs.io/ko/v0.4.3/) 이용해서 설치

만약 설치 없이 원하는 것들만 실행하기 위해서는

main.py에서 
1) import category_classifier을 주석처리한다.
2) class HotspotPlaceness와 class FeatureExtraction을 주석처리한다.

이 경우 위의 두 패키지에 따른 문제는 발생하지 않을 것으로 생각됩니다.

**Comment by shinbyh** [comment]
Readme에 반영하였습니다.
